- name: Instalar dependencias de Docker
  apt:
    name:
      - gnupg
      - lsb-release
    state: present

- name: Agregar llave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar repositorio de Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Actualizar cache de apt
  apt:
    update_cache: yes

- name: Instalar paquetes de Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Habilitar servicio de Docker
  systemd:
    name: docker
    enabled: yes

- name: Iniciar servicio de Docker
  systemd:
    name: docker
    state: started

- name: Agregar usuario admin al grupo docker
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: true
