# Core identity and access
admin_user: "kduran"
ssh_login_user: "{{ admin_user }}"
ssh_port: 22

# Bootstrap strategy
bootstrap_mode: "managed"
bootstrap_init_user: "root"

# Server identity
server_hostname: "kumadev"
