backup_enabled: true

backup_restic_repository: "s3:https://63d40405a3ee61d712afed2a4e733d1f.r2.cloudflarestorage.com/infra-bucket/restic-repo"
backup_aws_default_region: "auto"

backup_paths:
  - "{{ data_root }}"
  - "{{ stacks_root }}"
  - "{{ config_root }}/apps"

backup_excludes:
  - "{{ config_root }}/backup"
  - "{{ logs_root }}"
  - "{{ backups_root }}"
