netdata_release_channel: stable

netdata_port: 19999
netdata_bind_to: "127.0.0.1"  # fuerza acceso por túnel SSH / reverse proxy local
netdata_kickstart_path: "/tmp/netdata-kickstart.sh"

netdata_manage_firewall: true
netdata_allow_port: false  # por defecto NO abrir 19999
netdata_allow_ip: ""  # si algún día quieres permitir tu IP pública
