- name: Desplegar aplicaciones en ALTAIR
  hosts: servers
  become: true
  remote_user: "{{ ssh_login_user }}"
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/paths.yml
    - ../group_vars/apps.yml
    - ../group_vars/network.yml
    - ../group_vars/data-services.yml
  roles:
    - role: uptime-kuma
      tags: uptime-kuma
    - role: portfolio
      tags: portfolio
    - role: portainer
      tags: portainer
    - role: n8n
      tags: n8n
    - role: npm
      tags: npm
    - role: netdata
      tags: netdata
